Configured zap scan

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -105,12 +105,24 @@ jobs:
             # Step2: Install Java and Start ZAP in daemon mode
                 cd ZAP_2.14.0/
                 sudo yum install java-17 -y
+
+                check_zap_running() {
+                                curl -s "http://127.0.0.1:8080/JSON/core/view/version" > /dev/null
+                                return $?
+                            }
+
                 java -jar zap-2.14.0.jar -daemon -port 8080 -config api.disablekey=true &
                 sleep 30
-                if ! curl -s "http://127.0.0.1:8080/JSON/core/view/version"; then
-                    echo "ZAP did not start correctly."
-                    exit 1
-                fi
+              # Check if ZAP is running, retry up to 3 times if not
+                for i in {1..3}; do
+                    if check_zap_running; then
+                        echo "ZAP started successfully."
+                        break
+                    else
+                        echo "ZAP did not start correctly, retrying... ($i)"
+                        sleep 10  # Wait before retrying
+                    fi
+                done
 
             # Step3: Update and install necessary packages
                 sudo yum update -y
