Configured zap scan

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -130,13 +130,18 @@ jobs:
           # Step12: Wait for the scan to finish
             while true; do
               status=$(curl -s "http://127.0.0.1:8080/JSON/spider/view/status/?scanId=$scan_id" | jq -r '.status')
+              # Check if status is valid
+              if [[ -z "$status" || ! "$status" =~ ^[0-9]+$ ]]; then
+                  echo "Invalid status value: $status"
+                  exit 1
+              fi
               echo "Spider progress: $status%"
               if [ "$status" -eq 100 ]; then
                   echo "Spidering completed!"
                   break
               fi
               sleep 5
-            done
+          done
             
           # Step13: Get the report
             alerts=$(curl -s "http://127.0.0.1:8080/JSON/core/view/alerts/?baseurl=http://127.0.0.1:8000")
@@ -156,4 +161,3 @@ jobs:
           INSTANCE_ID=$(aws ec2 run-instances --image-id ami-078264b8ba71bc45e --count 1 --instance-type t2.micro --key-name AWS_KEY_PAIR_MUMBAI --security-group-ids sg-07afad8b77062b7a3 --query 'Instances[0].InstanceId' --output text)
           echo "Launched instance ID: $INSTANCE_ID"
           aws ec2 terminate-instances --instance-ids $INSTANCE_ID
-          
