updated original yaml file to include jbos

diff --git a/.github/workflows/original_deploy.yml b/.github/workflows/original_deploy.yml
--- a/.github/workflows/original_deploy.yml
+++ b/.github/workflows/original_deploy.yml
@@ -143,6 +143,7 @@ jobs:
     steps:
         - name: Host the Server
           run: |
+            EC2_IP=${{ steps.get_ip.outputs.ec2_ip }}
             ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -o ServerAliveCountMax=3 -i ~/.ssh/MyKeyPair.pem ec2-user@$EC2_IP <<EOF
                         
                 cd /home/ec2-user/cyberdemo/contactListApp
@@ -155,12 +156,13 @@ jobs:
                 else
                     echo "Failed to start Django server."
                     exit 1
-                    
+
                 fi
                             
             EOF    
         - name: Perform Zap scan
-          run: |       
+          run: |  
+              EC2_IP=${{ steps.get_ip.outputs.ec2_ip }}     
               ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -o ServerAliveCountMax=3 -i ~/.ssh/MyKeyPair.pem ec2-user@$EC2_IP <<EOF
                     chmod 777 /home/ec2-user/cyberdemo/contactListApp/contactListApp/zap_scripts/zap_scan.sh
                     bash /home/ec2-user/cyberdemo/contactListApp/contactListApp/zap_scripts/zap_scan.sh                
@@ -179,7 +181,8 @@ jobs:
 
         - name: Upload zap Scan Results
           run: |
-                scp -o StrictHostKeyChecking=no -i ~/.ssh/MyKeyPair.pem ec2-user@${{ steps.get_ip.outputs.ec2_ip }}:/home/ec2-user/ZAP_2.14.0/zap_scan_results.json ./zap_scan_results.json || { echo "SCP failed"; exit 1; }
+                EC2_IP=${{ steps.get_ip.outputs.ec2_ip }}
+                scp -o StrictHostKeyChecking=no -i ~/.ssh/MyKeyPair.pem ec2-user@$EC2_IP:/home/ec2-user/ZAP_2.14.0/zap_scan_results.json ./zap_scan_results.json || { echo "SCP failed"; exit 1; }
       
         - name: Verify Uploaded File
           run: |
@@ -203,4 +206,5 @@ jobs:
     steps:
       - name: Terminate EC2 Instance 
         run: |
+        
           aws ec2 terminate-instances --instance-ids ${{ steps.launch_ec2.outputs.instance_id }}
